
CREATE TABLE tb_editora (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    cnpj VARCHAR(255)

);

CREATE TABLE tb_resumo_livro (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto TEXT

);


CREATE TABLE tb_livro (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255),
    isbn VARCHAR(255),
    ano_publicacao INTEGER,
    editora_id BIGINT,
    resumo_id BIGINT UNIQUE,
    CONSTRAINT fk_livro_editora FOREIGN KEY (editora_id) REFERENCES tb_editora (id),
    CONSTRAINT fk_livro_resumo FOREIGN KEY (resumo_id) REFERENCES tb_resumo_livro (id)

);


CREATE TABLE tb_autor (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    nacionalidade VARCHAR(255)

);



CREATE TABLE tb_livro_autor (

    livro_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    CONSTRAINT pk_livro_autor PRIMARY KEY (livro_id, autor_id),
    CONSTRAINT fk_la_livro FOREIGN KEY (livro_id) REFERENCES tb_livro (id),
    CONSTRAINT fk_la_autor FOREIGN KEY (autor_id) REFERENCES tb_autor (id)

);