CREATE TABLE revinfo (
    rev INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    revtstmp BIGINT
);

CREATE SEQUENCE revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE tb_editora_aud (
    id BIGINT,
    rev INTEGER REFERENCES revinfo (rev),
    revtype SMALLINT,
    nome VARCHAR(255),
    cnpj VARCHAR(255),
    PRIMARY KEY (id, rev)
);

CREATE TABLE tb_resumo_livro_aud (
    id BIGINT,
    rev INTEGER REFERENCES revinfo (rev),
    revtype SMALLINT,
    texto TEXT,
    PRIMARY KEY (id, rev)
);

CREATE TABLE tb_livro_aud (

    id BIGINT,
    rev INTEGER REFERENCES revinfo (rev),
    revtype SMALLINT,
    titulo VARCHAR(255),
    isbn VARCHAR(255),
    ano_publicacao INTEGER,
    editora_id BIGINT,
    resumo_id BIGINT,
    PRIMARY KEY (id, rev)
);

CREATE TABLE tb_autor_aud (
    id BIGINT,
    rev INTEGER REFERENCES revinfo (rev),
    revtype SMALLINT,
    nome VARCHAR(255),
    nacionalidade VARCHAR(255),
    PRIMARY KEY (id, rev)
);

CREATE TABLE tb_livro_autor_aud (
    rev INTEGER REFERENCES revinfo (rev),
    revtype SMALLINT,
    livro_id BIGINT,
    autor_id BIGINT,
    PRIMARY KEY (livro_id, autor_id, rev)
);